config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :friends

      resources :shots

      resources :holes_results

      resources :rounds

      resources :holes_overviews

      resources :golf_courses

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "golf_courses#index"
  resources :friends
  resources :shots
  resources :holes_results
  resources :rounds
  resources :holes_overviews
  resources :golf_courses
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friend.rb
class Friend < ApplicationRecord
  # Direct associations

  belongs_to :friend,
             class_name: "User"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    friend.to_s
  end
end

app/controllers/api/v1/friends_controller.rb
class Api::V1::FriendsController < Api::V1::GraphitiController
  def index
    friends = FriendResource.all(params)
    respond_with(friends)
  end

  def show
    friend = FriendResource.find(params)
    respond_with(friend)
  end

  def create
    friend = FriendResource.build(params)

    if friend.save
      render jsonapi: friend, status: :created
    else
      render jsonapi_errors: friend
    end
  end

  def update
    friend = FriendResource.find(params)

    if friend.update_attributes
      render jsonapi: friend
    else
      render jsonapi_errors: friend
    end
  end

  def destroy
    friend = FriendResource.find(params)

    if friend.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: friend
    end
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]

  def index
    @q = Friend.ransack(params[:q])
    @friends = @q.result(distinct: true).includes(:friend).page(params[:page]).per(10)
  end

  def show; end

  def new
    @friend = Friend.new
  end

  def edit; end

  def create
    @friend = Friend.new(friend_params)

    if @friend.save
      message = "Friend was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @friend, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @friend.update(friend_params)
      redirect_to @friend, notice: "Friend was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @friend.destroy
    message = "Friend was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to friends_url, notice: message
    end
  end

  private

  def set_friend
    @friend = Friend.find(params[:id])
  end

  def friend_params
    params.require(:friend).permit(:friend_id)
  end
end

app/views/friends/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Friend #<%= friend.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Friend</dt>
      <dd>
        <% if @friend.friend.present? %>
          <%= link_to friend.friend, friend.friend %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back friend, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_friend_url(friend), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to friend, method: :delete, data: { confirm: "Do you really want to delete this friend?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(friend.updated_at) %> ago
  </div>
</div>

app/views/friends/_form.html.erb
<% was_validated = friend.errors.any? %>

<%= form_with(model: friend, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% friend_class = "form-control" %>
    <% friend_was_invalid = friend.errors.include?(:friend) %>

    <% if was_validated %>
      <% if friend_was_invalid %>
        <% friend_class << " is-invalid" %>
      <% else %>
        <% friend_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :friend_id %>
    <%= f.collection_select :friend_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if friend_was_invalid %>
      <% friend.errors.full_messages_for(:friend).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/friends/_friends_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "friends_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :friend_email_cont, "Friend email contains" %>
    <%= f.text_field :friend_email_cont, :class => "form-control", :placeholder => "Friend email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/friends" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#friends_filters">
  Show filters
</a>

app/views/friends/_list_item.html.erb
<%= link_to friend, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= friend %>
    <small class="text-muted">
      <%= time_ago_in_words(friend.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/friends/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Friend #<%= @friend.id %>
      </h2>

      <div class="card-body">
        <%= render "form", friend: @friend %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/friends/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Friends

      <%= link_to new_friend_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "friends/friends_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Friends

        <%= link_to new_friend_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @friends, partial: "list_item", as: :friend %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @friends, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/friends/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Friend
      </h2>

      <div class="card-body">
        <%= render "form", friend: @friend %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/friends/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @friend, partial: "card", as: :friend %>
  </div>
</div>