config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :friends

      resources :shots

      resources :holes_results

      resources :rounds

      resources :holes_overviews

      resources :golf_courses

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "golf_courses#index"
  resources :friends
  resources :shots
  resources :holes_results
  resources :rounds
  resources :holes_overviews
  resources :golf_courses
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/holes_overviews_controller.rb
class Api::V1::HolesOverviewsController < Api::V1::GraphitiController
  def index
    holes_overviews = HolesOverviewResource.all(params)
    respond_with(holes_overviews)
  end

  def show
    holes_overview = HolesOverviewResource.find(params)
    respond_with(holes_overview)
  end

  def create
    holes_overview = HolesOverviewResource.build(params)

    if holes_overview.save
      render jsonapi: holes_overview, status: :created
    else
      render jsonapi_errors: holes_overview
    end
  end

  def update
    holes_overview = HolesOverviewResource.find(params)

    if holes_overview.update_attributes
      render jsonapi: holes_overview
    else
      render jsonapi_errors: holes_overview
    end
  end

  def destroy
    holes_overview = HolesOverviewResource.find(params)

    if holes_overview.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: holes_overview
    end
  end
end

app/controllers/holes_overviews_controller.rb
class HolesOverviewsController < ApplicationController
  before_action :set_holes_overview, only: %i[show edit update destroy]

  def index
    @q = HolesOverview.ransack(params[:q])
    @holes_overviews = @q.result(distinct: true).includes(:golf_course).page(params[:page]).per(10)
  end

  def show; end

  def new
    @holes_overview = HolesOverview.new
  end

  def edit; end

  def create
    @holes_overview = HolesOverview.new(holes_overview_params)

    if @holes_overview.save
      message = "HolesOverview was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @holes_overview, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @holes_overview.update(holes_overview_params)
      redirect_to @holes_overview,
                  notice: "Holes overview was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @holes_overview.destroy
    message = "HolesOverview was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to holes_overviews_url, notice: message
    end
  end

  private

  def set_holes_overview
    @holes_overview = HolesOverview.find(params[:id])
  end

  def holes_overview_params
    params.require(:holes_overview).permit(:hole_number, :distance_to_hole,
                                           :distance_to_green, :golf_course_id)
  end
end

app/views/holes_overviews/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Holes Overview #<%= holes_overview.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Hole number</dt>
      <dd><%= holes_overview.hole_number %></dd>

      <dt>Distance to hole</dt>
      <dd><%= holes_overview.distance_to_hole %></dd>

      <dt>Distance to green</dt>
      <dd><%= holes_overview.distance_to_green %></dd>

      <dt>Golf course</dt>
      <dd>
        <% if @holes_overview.golf_course.present? %>
          <%= link_to holes_overview.golf_course, holes_overview.golf_course %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back holes_overview, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_holes_overview_url(holes_overview), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to holes_overview, method: :delete, data: { confirm: "Do you really want to delete this holes_overview?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(holes_overview.updated_at) %> ago
  </div>
</div>

app/views/holes_overviews/_form.html.erb
<% was_validated = holes_overview.errors.any? %>

<%= form_with(model: holes_overview, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% hole_number_class = "form-control" %>
    <% hole_number_was_invalid = holes_overview.errors.include?(:hole_number) %>

    <% if was_validated %>
      <% if hole_number_was_invalid %>
        <% hole_number_class << " is-invalid" %>
      <% else %>
        <% hole_number_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :hole_number %>
    <%= f.number_field :hole_number, class: hole_number_class, placeholder: "Enter hole number" %>
    <% if hole_number_was_invalid %>
      <% holes_overview.errors.full_messages_for(:hole_number).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% distance_to_hole_class = "form-control" %>
    <% distance_to_hole_was_invalid = holes_overview.errors.include?(:distance_to_hole) %>

    <% if was_validated %>
      <% if distance_to_hole_was_invalid %>
        <% distance_to_hole_class << " is-invalid" %>
      <% else %>
        <% distance_to_hole_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :distance_to_hole %>
    <%= f.text_field :distance_to_hole, class: distance_to_hole_class, placeholder: "Enter distance to hole" %>
    <% if distance_to_hole_was_invalid %>
      <% holes_overview.errors.full_messages_for(:distance_to_hole).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% distance_to_green_class = "form-control" %>
    <% distance_to_green_was_invalid = holes_overview.errors.include?(:distance_to_green) %>

    <% if was_validated %>
      <% if distance_to_green_was_invalid %>
        <% distance_to_green_class << " is-invalid" %>
      <% else %>
        <% distance_to_green_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :distance_to_green %>
    <%= f.text_field :distance_to_green, class: distance_to_green_class, placeholder: "Enter distance to green" %>
    <% if distance_to_green_was_invalid %>
      <% holes_overview.errors.full_messages_for(:distance_to_green).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% golf_course_class = "form-control" %>
    <% golf_course_was_invalid = holes_overview.errors.include?(:golf_course) %>

    <% if was_validated %>
      <% if golf_course_was_invalid %>
        <% golf_course_class << " is-invalid" %>
      <% else %>
        <% golf_course_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :golf_course_id %>
    <%= f.collection_select :golf_course_id, GolfCourse.all, :id, :to_s, {}, class: "form-control" %>
    <% if golf_course_was_invalid %>
      <% holes_overview.errors.full_messages_for(:golf_course).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/holes_overviews/_holes_overviews_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "holes_overviews_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :hole_number, "Hole number" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :hole_number_gteq, :class => "form-control", :placeholder => "Hole number greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :hole_number_lteq, :class => "form-control", :placeholder => "Hole number less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :distance_to_green, "Distance to green" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :distance_to_green_gteq, :class => "form-control", :placeholder => "Distance to green greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :distance_to_green_lteq, :class => "form-control", :placeholder => "Distance to green less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :distance_to_hole, "Distance to hole" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :distance_to_hole_gteq, :class => "form-control", :placeholder => "Distance to hole greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :distance_to_hole_lteq, :class => "form-control", :placeholder => "Distance to hole less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :golf_course_name_cont, "Golf course name contains" %>
    <%= f.text_field :golf_course_name_cont, :class => "form-control", :placeholder => "Golf course name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/holes_overviews" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#holes_overviews_filters">
  Show filters
</a>

app/views/holes_overviews/_list_item.html.erb
<%= link_to holes_overview, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= holes_overview %>
    <small class="text-muted">
      <%= time_ago_in_words(holes_overview.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/holes_overviews/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Holes Overview #<%= @holes_overview.id %>
      </h2>

      <div class="card-body">
        <%= render "form", holes_overview: @holes_overview %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/holes_overviews/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Holes Overviews

      <%= link_to new_holes_overview_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "holes_overviews/holes_overviews_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Holes Overviews

        <%= link_to new_holes_overview_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @holes_overviews, partial: "list_item", as: :holes_overview %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @holes_overviews, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/holes_overviews/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Holes Overview
      </h2>

      <div class="card-body">
        <%= render "form", holes_overview: @holes_overview %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/holes_overviews/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @holes_overview, partial: "card", as: :holes_overview %>
  </div>
</div>